sudo: required
services:
  - docker

before_install:
  - docker build -t adamgorse/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t adamgorse/multi-client ./client
  - docker build -t adamgorse/multi-nginx ./nginx
  - docker build -t adamgorse/multi-server ./server
  - docker build -t adamgorse/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take images and push to docker hub
  - docker push adamgorse/multi-client
  - docker push adamgorse/multi-nginx
  - docker push adamgorse/multi-server
  - docker push adamgorse/multi-worker
  
